version: '3.8'

services:
  # Production environment
  vuejs-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production