version: '3.8'

services:
  # Development environment
  vuejs-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/web
    environment:
      NODE_ENV: development